### ISSUE TITLE
Make email as argument

### ISSUE THREAD

**Issue by andreaschandra** [RussellDash332/email-automation#1]
https://github.com/RussellDash332/email-automation/blob/5b66bc6dfe737867951f39e0a592c466bf8fbec5/main.py#L21-L22

change this static variable to dynamic using user input as in file arguments.

Or add to read email files

**Comment by RussellDash332** [comment]
Thanks for the issue. Currently I'm not trying to read emails, but rather trying to send emails of the send format repeatedly 😆
